name: NeghabBardar
description: یک اپلیکیشن برای شناسایی تصاویر دیپ‌فیک
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  bitsdojo_window: ^0.1.5
  file_picker: ^6.1.1
  http: ^1.2.1
  google_fonts: ^6.1.0
  animated_background: ^2.0.0
  url_launcher: ^6.2.1
  
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Regular.ttf
